import PublicLegalShell from '../components/PublicLegalShell';

export const metadata = {
  title: 'Privacy Policy — USAMPAC',
  description: 'How the USAMPAC iOS app collects and uses information'
};

export default function PrivacyPage() {
  return (
    <PublicLegalShell title="Privacy Policy">
      <p className="muted">Effective August 23, 2026</p>

      <h2>Who we are</h2>
      <p>
        USAMPAC (American Muslim Public Affairs Committee) publishes the USAMPAC iOS app so
        voters can browse candidates and elected officials, vote in polls, take a civics quiz,
        and receive election notifications. This policy describes information collected by that
        app and the systems that support it.
      </p>

      <h2>What we collect</h2>
      <p>
        You can browse candidates and elected officials as a guest without creating an account.
      </p>
      <p>
        If you register as a candidate or elected official, we collect the information you
        enter on the registration and profile screens, including:
      </p>
      <ul>
        <li>Name</li>
        <li>Email address (from your account)</li>
        <li>Phone number (optional)</li>
        <li>Photo (optional)</li>
        <li>Office, election cycle, party, city, and state</li>
        <li>Biography, campaign priorities, and website or social links you provide</li>
        <li>Campaign filing numbers you choose to submit (used for review, not shown in the public app listing)</li>
      </ul>
      <p>
        The registration form states that your email and phone appear on your public candidate
        profile so voters can contact you. Phone is optional; leave it blank if you do not want
        it published.
      </p>
      <p>If you take part in polls, we also store:</p>
      <ul>
        <li>
          A device identifier generated by Apple for this vendor (
          <code>identifierForVendor</code>), used only to associate a vote with a device so the
          same device cannot vote twice in the same poll
        </li>
      </ul>
      <p>On the device, the app stores:</p>
      <ul>
        <li>Sign-in tokens, so you stay logged in</li>
        <li>Whether you are browsing as a guest or as a candidate</li>
      </ul>

      <h2>How we use it</h2>
      <ul>
        <li>To list approved candidates and elected officials in the app</li>
        <li>To let voters contact candidates through the email or phone the candidate published</li>
        <li>To operate polls, the civics quiz, and election notifications</li>
        <li>To review candidate applications before they appear publicly</li>
        <li>To keep you signed in on this device</li>
      </ul>
      <p>We do not sell personal information. We do not use it for third-party advertising.</p>

      <h2>What is public</h2>
      <p>
        After a candidate or elected official profile is approved, the name, office, location,
        photo, biography, links, email, and phone they provided are visible to anyone using the
        app. Reviewer notes and unpublished applications are not part of the public listing.
      </p>

      <h2>Where it is stored</h2>
      <p>
        Account and profile data are stored with our database provider (Supabase). Sign-in
        tokens stay on your device. We keep information as long as the account or listing is
        active, or as needed to operate the app and meet legal obligations.
      </p>

      <h2>Your choices</h2>
      <ul>
        <li>Browse as a guest without registering</li>
        <li>Leave phone blank if you do not want it published</li>
        <li>Edit your profile from the app after you sign in</li>
        <li>
          Ask us to correct or remove a listing by using the{' '}
          <a href="/support">Support</a> page
        </li>
      </ul>

      <h2>Children</h2>
      <p>
        The app is intended for a general audience. We do not knowingly collect personal
        information from children under 13. If you believe we have, contact us through Support
        and we will delete it.
      </p>

      <h2>Changes</h2>
      <p>
        If this policy changes, we will update this page and the effective date. Continued use
        of the app after a change means you accept the updated policy.
      </p>

      <h2>Contact</h2>
      <p>
        Privacy questions: see <a href="/support">Support</a>. Organization website:{' '}
        <a href="https://usampac.org">usampac.org</a>.
      </p>
    </PublicLegalShell>
  );
}
